[package]
name = "fastbloom"
version = "0.1.0"
edition = "2021"
authors = ["tomtomwombat"]
description = "The fastest bloom filter in Rust. No accuracy compromises. Compatible with any hasher."
license = "MIT OR Apache-2.0"
homepage = "https://github.com/tomtomwombat/fastbloom/"
repository = "https://github.com/tomtomwombat/fastbloom/"
keywords = ["bloom", "filter", "data-structures", "bloom-filter", "bloomfilter"]
categories = ["data-structures", "caching", "algorithms"]
readme = "README.md"
exclude = ["benches/*"]

[badges]
maintenance = { status = "actively-developed"}

[dependencies]
rand = "0.8.5"
siphasher = "1.0.0"

[dev-dependencies]
rand_regex = "0.16.0"
criterion = { version = "0.4", features = ["html_reports"] }
ahash = "0.8.6"

[[bench]]
name = "bench_main"
harness = false
