[package]
name = "fastbloom"
version = "0.2.0"
edition = "2021"
authors = ["tomtomwombat"]
description = "The fastest bloom filter in Rust. No accuracy compromises. Compatible with any hasher."
license = "MIT OR Apache-2.0"
homepage = "https://github.com/tomtomwombat/fastbloom/"
repository = "https://github.com/tomtomwombat/fastbloom/"
keywords = ["bloom", "filter", "data-structures", "bloom-filter", "bloomfilter"]
categories = ["data-structures", "caching", "algorithms"]
readme = "README.md"

[badges]
maintenance = { status = "actively-developed"}

[dependencies]
rand = "0.8.5"
siphasher = "1.0.0"

[dev-dependencies]
rand_regex = "0.16.0"
ahash = "0.8.6"
criterion = { version = "0.5.1", features = ["html_reports"] }
bloom = "0.3.2"
bloomfilter = "1.0.13"
probabilistic-collections = "0.7.0"
fastbloom-rs = "0.5.9"

[[bench]]
name = "bench_bloom_filter"
harness = false
